# Generated by Django 6.0 on 2026-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_city_attraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание тура')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность (например, 7 дней)')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
