# Generated by Django 6.0 on 2026-04-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Длительность'),
        ),
    ]
